const menu = {
    list() {
        return [
    {
        "backMenu":[
            {
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"管理员管理",
                        "menuJump":"列表",
                        "tableName":"users"
                    }
                ],
                "menu":"管理员管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "删除",
                            "修改"
                        ],
                        "menu":"公告类型管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryGonggao"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "删除",
                            "修改"
                        ],
                        "menu":"项目类型管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryLixiang"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "删除",
                            "修改"
                        ],
                        "menu":"项目评审类型管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryLixiangPingshen"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "删除",
                            "修改"
                        ],
                        "menu":"商机类型管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryShangji"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "删除",
                            "修改"
                        ],
                        "menu":"商机等级管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryShangjiDengji"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "删除",
                            "修改"
                        ],
                        "menu":"商机跟进类型管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryShangjiGenjin"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "删除",
                            "修改"
                        ],
                        "menu":"商机转化类型管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryShangjiZhuanhua"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "删除",
                            "修改"
                        ],
                        "menu":"线索类型管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryXiansuo"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "删除",
                            "修改"
                        ],
                        "menu":"线索等级管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryXiansuoDengji"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "删除",
                            "修改"
                        ],
                        "menu":"线索跟进类型管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryXiansuoGenjin"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "删除",
                            "修改"
                        ],
                        "menu":"线索转化类型管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryXiansuoZhuanhua"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "删除",
                            "修改"
                        ],
                        "menu":"招标类型管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryZhaobiao"
                    }
                ],
                "menu":"基础数据管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"公告信息管理",
                        "menuJump":"列表",
                        "tableName":"gonggao"
                    }
                ],
                "menu":"公告信息管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"项目立项管理",
                        "menuJump":"列表",
                        "tableName":"lixiang"
                    }
                ],
                "menu":"项目立项管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"合同签署管理",
                        "menuJump":"列表",
                        "tableName":"hetongqianshu"
                    }
                ],
                "menu":"合同签署管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"项目跟进管理",
                        "menuJump":"列表",
                        "tableName":"lixiangGenjin"
                    }
                ],
                "menu":"项目跟进管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"项目评审管理",
                        "menuJump":"列表",
                        "tableName":"lixiangPingshen"
                    }
                ],
                "menu":"项目评审管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"项目验收管理",
                        "menuJump":"列表",
                        "tableName":"lixiangyanshou"
                    }
                ],
                "menu":"项目验收管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"商机管理",
                        "menuJump":"列表",
                        "tableName":"shangji"
                    }
					,
					 {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"商机跟进管理",
                        "menuJump":"列表",
                        "tableName":"shangjiGenjin"
                    }
					,
					{
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"商机转化管理",
                        "menuJump":"列表",
                        "tableName":"shangjiZhuanhua"
                    }
                ],
                "menu":"商机管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"线索管理",
                        "menuJump":"列表",
                        "tableName":"xiansuo"
                    }
					,
					{
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"线索跟进管理",
                        "menuJump":"列表",
                        "tableName":"xiansuoGenjin"
                    }
					,
					{
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"线索转化管理",
                        "menuJump":"列表",
                        "tableName":"xiansuoZhuanhua"
                    }
                ],
                "menu":"线索管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"招标管理",
                        "menuJump":"列表",
                        "tableName":"zhaobiao"
                    }
					,
					{
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"投标管理",
                        "menuJump":"列表",
                        "tableName":"zhaobiaoToubiao"
                    }
                ],
                "menu":"招标管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"用户管理",
                        "menuJump":"列表",
                        "tableName":"yonghu"
                    }
					,
					{
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"企业管理",
                        "menuJump":"列表",
                        "tableName":"qiye"
                    }
                ],
                "menu":"用户管理"
            }
        ],
        "frontMenu":[],
        "hasBackLogin":"是",
        "hasBackRegister":"否",
        "hasFrontLogin":"否",
        "hasFrontRegister":"否",
        "roleName":"管理员",
        "tableName":"users"
    }
	,
	{
        "backMenu":[
           {
                "child":[
                    {
                        "buttons":[
                            "查看"
                        ],
                        "menu":"公告信息管理",
                        "menuJump":"列表",
                        "tableName":"gonggao"
                    }
                ],
                "menu":"公告信息管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增"
                        ],
                        "menu":"项目立项管理",
                        "menuJump":"列表",
                        "tableName":"lixiang"
                    }
                ],
                "menu":"项目立项管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增"
                        ],
                        "menu":"合同签署管理",
                        "menuJump":"列表",
                        "tableName":"hetongqianshu"
                    }
                ],
                "menu":"合同签署管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增"
                        ],
                        "menu":"项目跟进管理",
                        "menuJump":"列表",
                        "tableName":"lixiangGenjin"
                    }
                ],
                "menu":"项目跟进管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增"
                        ],
                        "menu":"项目评审管理",
                        "menuJump":"列表",
                        "tableName":"lixiangPingshen"
                    }
                ],
                "menu":"项目评审管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增"
                        ],
                        "menu":"项目验收管理",
                        "menuJump":"列表",
                        "tableName":"lixiangyanshou"
                    }
                ],
                "menu":"项目验收管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"商机管理",
                        "menuJump":"列表",
                        "tableName":"shangji"
                    }
					,
					 {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"商机跟进管理",
                        "menuJump":"列表",
                        "tableName":"shangjiGenjin"
                    }
					,
					{
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"商机转化管理",
                        "menuJump":"列表",
                        "tableName":"shangjiZhuanhua"
                    }
                ],
                "menu":"商机管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"线索管理",
                        "menuJump":"列表",
                        "tableName":"xiansuo"
                    }
					,
					{
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"线索跟进管理",
                        "menuJump":"列表",
                        "tableName":"xiansuoGenjin"
                    }
					,
					{
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"线索转化管理",
                        "menuJump":"列表",
                        "tableName":"xiansuoZhuanhua"
                    }
                ],
                "menu":"线索管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看"
                        ],
                        "menu":"招标管理",
                        "menuJump":"列表",
                        "tableName":"zhaobiao"
                    }
					,
					{
                        "buttons":[
                            "查看",
                            "新增"
                        ],
                        "menu":"投标管理",
                        "menuJump":"列表",
                        "tableName":"zhaobiaoToubiao"
                    }
                ],
                "menu":"招标管理"
            }
        ],
        "frontMenu":[],
        "hasBackLogin":"是",
        "hasBackRegister":"否",
        "hasFrontLogin":"否",
        "hasFrontRegister":"否",
        "roleName":"用户",
        "tableName":"yonghu"
    }
	,
	{
        "backMenu":[
            {
                "child":[
                    {
                        "buttons":[
                            "查看"
                        ],
                        "menu":"公告信息管理",
                        "menuJump":"列表",
                        "tableName":"gonggao"
                    }
                ],
                "menu":"公告信息管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "审核"
                        ],
                        "menu":"项目立项管理",
                        "menuJump":"列表",
                        "tableName":"lixiang"
                    }
                ],
                "menu":"项目立项管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "审核"
                        ],
                        "menu":"合同签署管理",
                        "menuJump":"列表",
                        "tableName":"hetongqianshu"
                    }
                ],
                "menu":"合同签署管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看"
                        ],
                        "menu":"项目跟进管理",
                        "menuJump":"列表",
                        "tableName":"lixiangGenjin"
                    }
                ],
                "menu":"项目跟进管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "审核"
                        ],
                        "menu":"项目评审管理",
                        "menuJump":"列表",
                        "tableName":"lixiangPingshen"
                    }
                ],
                "menu":"项目评审管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "审核"
                        ],
                        "menu":"项目验收管理",
                        "menuJump":"列表",
                        "tableName":"lixiangyanshou"
                    }
                ],
                "menu":"项目验收管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "报表"
                        ],
                        "menu":"商机管理",
                        "menuJump":"列表",
                        "tableName":"shangji"
                    }
					,
					 {
                        "buttons":[
                            "查看"
                        ],
                        "menu":"商机跟进管理",
                        "menuJump":"列表",
                        "tableName":"shangjiGenjin"
                    }
					,
					{
                        "buttons":[
                            "查看"
                        ],
                        "menu":"商机转化管理",
                        "menuJump":"列表",
                        "tableName":"shangjiZhuanhua"
                    }
                ],
                "menu":"商机管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看"
                        ],
                        "menu":"线索管理",
                        "menuJump":"列表",
                        "tableName":"xiansuo"
                    }
					,
					{
                        "buttons":[
                            "查看"
                        ],
                        "menu":"线索跟进管理",
                        "menuJump":"列表",
                        "tableName":"xiansuoGenjin"
                    }
					,
					{
                        "buttons":[
                            "查看"
                        ],
                        "menu":"线索转化管理",
                        "menuJump":"列表",
                        "tableName":"xiansuoZhuanhua"
                    }
                ],
                "menu":"线索管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"招标管理",
                        "menuJump":"列表",
                        "tableName":"zhaobiao"
                    }
					,
					{
                        "buttons":[
                            "查看",
                            "审核"
                        ],
                        "menu":"投标管理",
                        "menuJump":"列表",
                        "tableName":"zhaobiaoToubiao"
                    }
                ],
                "menu":"招标管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"用户管理",
                        "menuJump":"列表",
                        "tableName":"yonghu"
                    }
                ],
                "menu":"用户管理"
            }
        ],
        "frontMenu":[],
        "hasBackLogin":"是",
        "hasBackRegister":"否",
        "hasFrontLogin":"否",
        "hasFrontRegister":"否",
        "roleName":"企业",
        "tableName":"qiye"
    }
]
    }
}
export default menu;
